// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Actions: typeof import('./components/Actions.vue')['default']
    DiskInfo: typeof import('./components/DiskInfo.vue')['default']
    DocHeader: typeof import('./components/DocHeader.vue')['default']
    DocSideBar: typeof import('./components/DocSideBar.vue')['default']
    ExportModal: typeof import('./components/ExportModal.vue')['default']
    Ext4Component: typeof import('./components/Ext4/Ext4Component.vue')['default']
    FatTable: typeof import('./components/Fat/FatTable.vue')['default']
    FileBlocks: typeof import('./components/FileBlocks.vue')['default']
    FileExplorer: typeof import('./components/FileExplorer.vue')['default']
    FileInput: typeof import('./components/FileInput.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ImportModal: typeof import('./components/ImportModal.vue')['default']
    Log: typeof import('./components/Log.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenAlert: typeof import('./components/ScreenAlert.vue')['default']
    VolumeBlocks: typeof import('./components/VolumeBlocks.vue')['default']
  }
}

export {}
